Team.create(name: 'France', short_name: 'FRA')
Team.create(name: 'Allemagne', short_name: 'ALL')
Team.create(name: 'Norvège', short_name: 'NOR')
Team.create(name: 'Russie', short_name: 'RUS')
Team.create(name: 'Suisse', short_name: 'SUI')
Team.create(name: 'Italie', short_name: 'ITA')
Team.create(name: 'Finlande', short_name: 'FIN')
